[package]
name = "sign-cert-remote"
version = "0.1.0"
edition = "2018"

[dependencies]
rcgen = { version = "0.10", features = ["pem", "x509-parser"] }
x509-parser = { version = "0.15", features = ["verify"] }
